name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install frontend dependencies
      working-directory: password-manager-frontend
      run: yarn install

    - name: Lint frontend code
      working-directory: password-manager-frontend
      run: yarn lint

    - name: Install backend dependencies
      working-directory: password-manager-backend
      run: yarn install

    - name: Lint backend code
      working-directory: password-manager-backend
      run: yarn lint

